### ISSUE TITLE
Device Naming Issues

### ISSUE THREAD

**Issue by demonspork** [maykar/plex_assistant#30]
The sensor.plex_assistant_devices shows 
`Connected Devices:
  Cast Devices:
    - Living Room`

But I keep getting in the logs an error `2020-07-06 15:41:09 WARNING (SyncWorker_17) [custom_components.plex_assistant] Cast device not found: "Living Room"`

which is odd because there is definitely a device named Living Room. It is a Chromecast, and it works otherwise with plex just not using this integration. Any thoughts on what to try?

**Comment by maykar** [comment]
Give the latest version a try ( 0.1.8 )

**Comment by demonspork** [comment]
Still the same error. Thanks for looking at it!

**Comment by demonspork** [comment]
New log errors with 0.1.9

```
2020-07-06 22:59:45 ERROR (MainThread) [homeassistant.components.automation] Plex Assistant Automation: Error executing script. Unexpected error for call_service at pos 1: 'bool' object has no attribute 'title'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/fuzzywuzzy/process.py", line 93, in extractWithoutOrder
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/plex_assistant/__init__.py", line 120, in handle_input
    alias = fuzzy(command["device"] or default_cast, PA.alias_names)
  File "/config/custom_components/plex_assistant/helpers.py", line 42, in fuzzy
    return fw.extractOne(media, lib, scorer=scorer)
  File "/usr/local/lib/python3.7/site-packages/fuzzywuzzy/process.py", line 245, in extractOne
    return max(best_list, key=lambda i: i[1])
RuntimeError: generator raised StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 153, in _async_step
    self, f"_async_{cv.determine_script_action(self._action)}_step"
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 656, in _async_call_service_step
    *self._prep_call_service_step(), blocking=True, context=self._context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1259, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1298, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/plex_assistant/__init__.py", line 134, in handle_input
    command["device"].title()
AttributeError: 'bool' object has no attribute 'title'
2020-07-06 23:00:19 WARNING (SyncWorker_6) [custom_components.plex_assistant] Cast device not found: "Living Room"
```

**Comment by maykar** [comment]
Is this still an issue with the latest version (0.2.1)?

**Comment by demonspork** [comment]
Success! Now I can recommend this project when people keep posting in the Phlex project asking if it is going to be resurrected!

Plex announced they were working on this capability like 2.5 years ago and not a peep since. Thanks for filling in the gaps!
